### ISSUE TITLE
Change Barnes & Noble Search LInk

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/otherpress.com#7]
Barnes & Noble changed the link they use for search, so the link we use on sites for users to purchase BN books is now wrong. 

Current link (that we generate with the ISBN):

`http://search.barnesandnoble.com/booksearch/isbnInquiry.asp?EAN=9781635420128`

correct link:

`https://www.barnesandnoble.com/w/?ean=9781635420128`

**Comment by AdamChlan** [comment]
all set. closing out.
